# Generated by Django 3.1.1 on 2020-10-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=25)),
                ('Dt', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
