# Generated by Django 3.1.1 on 2020-10-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=25)),
                ('Dt', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
